title: Here Be Dragons
email: hashhar_blog@outlook.com
description: >
  Programming and social factors.
  A blog about programming, customising development environments and troubleshooting
  weird issues so that you don't have to. There may be occasional kittens and puppers.
baseurl: ""
url: ""
twitter_username: hashhar
github_username: hashhar

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
