title: Here Be Dragons
email:
description: >
  Programming and social factors.
  A blog about programming, customising development environments and troubleshooting
  weird issues so that you don't have to. There may be occasional kittens and puppers.
baseurl: ""
url: ""
twitter_username: hashhar
github_username: hashhar
permalink: /:title/
repository: hashhar/hashhar.github.io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.cmd
  - getruby.cmd
  - Rakefile
